### ISSUE TITLE
Treat id as another parameter

### ISSUE THREAD

**Issue by roberthoner** [payout/rester#13]
Currently, we create a helper method to retrieve the id so it can be accessed in instance methods. I think it'd be more consistent if the id were put the params hash before calling the method.  The key should equal the value returned by `Object::id_param` (e.g., "object_id" instead of just "id").

This would also be nice since the id could be validated like any other parameter and also potentially have the type changed to something more appropriate than a string.

**Comment by kayvonghaffari** [comment]
I really like this. It's definitely cleaner.
