### ISSUE TITLE
Provide clearer error when an Array or Hash is expected

### ISSUE THREAD

**Issue by kayvonghaffari** [payout/rester#77]
I came across this error message: `undefined method 'parse' for Array:Class` when sending a String for an Array param:

```ruby
params do
  Array   :array, type: String
end
```

` let(:params) {{ array: 'value' }} `

The undefined method error should be rescued and a more descriptive error message should be displayed

**Comment by roberthoner** [comment]
I don't think this is really an issue with the parse error.  The main issue here is that it's giving a parse error at all for this case.

This should cause a validation error that says something like `:array should be an array but a String was provided` or `:hash should be a hash but a String was provided`.
