### ISSUE TITLE
Need to be able to require params only for certain endpoints

### ISSUE THREAD

**Issue by roberthoner** [payout/rester#9]
Currently, when a param is required, it's required for each method, but this will rarely apply.  For example, when creating a record, there are many fields that may be required, but those same fields aren't going to be required when searching or retrieving a record.

I propose moving the "required" validation from the params validation and into a separate DSL:

```ruby
class MyObject < Rester::Service::Object
  params do
    String :name
  end

  requires :name
  def self.create(params)
    # Do stuff requiring name
  end

  def get
    # Return record, we don't need name here!
  end
end
```

**Comment by roberthoner** [comment]
Actually, the DSL I proposed may not be possible for class methods. It'll work for instance methods like `get` but I'm not sure about `create`.

**Comment by kayvonghaffari** [comment]
How about:
```
params do
  String :name, required_in: [:create, :search]
end
```

**Comment by roberthoner** [comment]
Closing this in favor of #15.
